[["runinfo"]]
run_number   = 123660
run_type     = 2             # "cosmics"
event_mode   = 1             # ran in onspill mode, 1=onspill
cfo_rate     = 4000.0        # CFO HB rate, Hz
ew_length    = 100.0e-6      # event window, sec
trigger_rate = 325.0         # rate to disk, Hz

[["runinfo"]]
# TRK+CALO+CRV (a mix of 123680 and 123681 (calo only trigger)
run_number   = 123680
run_type     = 2             # "cosmics"
event_mode   = 0             # off-spill
cfo_rate     = 4000.0        # CFO HB rate, Hz
ew_length    = 250.0e-6      # event window, sec
trigger_rate = 745.0         # rate to disk, Hz
dt_crv_trk   = 551.7         # ns, to be subtracted from the CRV pulse time
