[["runinfo"]]
run_number   = 124040
run_type     = 2             # "cosmics"
event_mode   = 1             # ran in offspill mode
cfo_rate     = 10000.0       # CFO HB rate, Hz
ew_length    = 100.0e-6      # event window, sec
trigger_rate = 740.0         # rate to disk, Hz, approx (from the DL log)

[["runinfo"]]
run_number   = 124041
run_type     = 2             # "cosmics"
event_mode   = 1             # ran in offspill mode
cfo_rate     = 10000.0       # CFO HB rate, Hz
ew_length    = 100.0e-6      # event window, sec
trigger_rate = 740.0         # rate to disk, Hz, approx (from the DL log)

[["runinfo"]]
run_number   = 124080
run_type     = 2             # "cosmics"
event_mode   = 1             # ran in offspill mode
cfo_rate     = 10000.0       # CFO HB rate, Hz
ew_length    = 100.0e-6      # event window, sec
trigger_rate = 880.0         # rate to disk, Hz, approx (from the DL log)

[["runinfo"]]
run_number   = 124081
run_type     = 2             # "cosmics"
event_mode   = 1             # ran in offspill mode
cfo_rate     = 10000.0       # CFO HB rate, Hz
ew_length    = 100.0e-6      # event window, sec
trigger_rate = 870.0         # rate to disk, Hz, approx (from the DL log)

[["runinfo"]]
run_number   = 124085
run_type     = 2             # "cosmics"
event_mode   = 1             # ran in offspill mode
cfo_rate     = 10000.0       # CFO HB rate, Hz
ew_length    = 100.0e-6      # event window, sec
trigger_rate = 480.0         # rate to disk, Hz, approx (from the DL log)

[["runinfo"]]
run_number   = 124093
run_type     = 2             # "cosmics"
event_mode   = 1             # ran in offspill mode
cfo_rate     = 10000.0       # CFO HB rate, Hz
ew_length    = 100.0e-6      # event window, sec
trigger_rate = 460.0         # rate to disk, Hz, approx (from the DL log)

[["runinfo"]]
run_number   = 124111
run_type     = 2             # "cosmics"
event_mode   = 1             # ran in offspill mode
cfo_rate     = 10000.0       # CFO HB rate, Hz
ew_length    = 100.0e-6      # event window, sec
trigger_rate = 490.0         # rate to disk, Hz, approx (from the DL log)

[["runinfo"]]
run_number   = 124117
run_type     = 2             # "cosmics"
event_mode   = 1             # ran in offspill mode
cfo_rate     = 10000.0       # CFO HB rate, Hz
ew_length    = 100.0e-6      # event window, sec
trigger_rate = 490.0         # rate to disk, Hz, approx (from the DL log)
dt_crv_trk   = 530.0         # ns, to be subtracted from CRV pulse

[["runinfo"]]
run_number   = 124155
run_type     = 2             # "cosmics"
event_mode   = 1             # ran in offspill mode
cfo_rate     = 10000.0       # CFO HB rate, Hz
ew_length    = 100.0e-6      # event window, sec
trigger_rate = 475.0         # rate to disk, Hz, approx (from the DL log)
dt_crv_trk   = 535.0         # ns, to be subtracted from CRV pulse
max_ewtag    = 216000000     # max event window tag (no exact, for histogramming)
